---
    - name: Tag instances
      local_action: ec2_tag resource= region={{ region }} state=present
      with_items: ec2_spot.instances
      args:
        tags:
          Spot: '{{ spot.stdout_lines[0] }}'